// export const ADD_BOOKMARK = 'ADD_BOOKMARK';
// export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';


export const SEARCH_INPUT = 'SEARCH_INPUT';
export const PRODUCT_DATA_LOADING = 'PRODUCT_DATA_LOADING';
export const PRODUCT_DATA_LOADED = 'PRODUCT_DATA_LOADED';