// export const ADD_BOOKMARK = 'ADD_BOOKMARK';
// export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';


export const SEARCH_INPUT = 'SEARCH_INPUT';

// PRODUCT REDUCER 
export const PRODUCT_DATA_LOADING = 'PRODUCT_DATA_LOADING';
export const PRODUCT_DATA_LOADED = 'PRODUCT_DATA_LOADED';

// CART REDUCER
export const CART_ADD_DATA = 'CART_ADD_DATA';